#!/bin/bash

# sudo npm install -g markdown-styles

cat ./input/*.md > recipes.md;
generate-md --layout mixu-bootstrap-2col --output ./output --input ./recipes.md;
rm recipes.md
rm -r ../assets
mv ./output/* ../
echo ">>> Yup, close enough."